// <auto-generated />
using System;
using AllItems.Translation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AllItems.Translation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AllItems.Translation.Core.Domain.ApiUsageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharacterCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("YearMonth")
                        .IsUnique();

                    b.ToTable("ApiUsageRecords");
                });

            modelBuilder.Entity("AllItems.Translation.Core.Domain.SentenceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedSourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceLanguage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetLanguage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceLanguage", "TargetLanguage", "NormalizedSourceText")
                        .IsUnique();

                    b.ToTable("SentenceTranslations");
                });

            modelBuilder.Entity("AllItems.Translation.Core.Domain.WordEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Language", "NormalizedText")
                        .IsUnique();

                    b.ToTable("WordEntries");
                });

            modelBuilder.Entity("AllItems.Translation.Core.Domain.WordTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetLanguage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WordEntryId", "TargetLanguage");

                    b.ToTable("WordTranslations");
                });

            modelBuilder.Entity("AllItems.Translation.Core.Domain.WordTranslation", b =>
                {
                    b.HasOne("AllItems.Translation.Core.Domain.WordEntry", "WordEntry")
                        .WithMany("Translations")
                        .HasForeignKey("WordEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WordEntry");
                });

            modelBuilder.Entity("AllItems.Translation.Core.Domain.WordEntry", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
